import { Category, MenuItem } from "../../types/restaurant";

export interface MenuTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  defaultAccentColor: string;
  categories: Category[];
  items: MenuItem[];
}

export const ONBOARDING_TEMPLATES: MenuTemplate[] = [
  {
    id: "template_pizzeria",
    name: "Italienische Pizzeria & Trattoria",
    description: "Klassische Steinofen-Pizzen in 2 Größen, Pasta, Insalata, Tiramisu und Kaltgetränke.",
    icon: "🍕",
    defaultAccentColor: "#c2410c",
    categories: [
      { id: "cat_piz", name: "Steinofen-Pizza", description: "Frisch zubereitet aus handgezogenem Teig mit 48h Teigführung", order: 1 },
      { id: "cat_pasta", name: "Frische Pasta", description: "Handgemachte Nudeln mit traditionellen italienischen Saucen", order: 2 },
      { id: "cat_salad", name: "Insalate & Vorspeisen", description: "Knackfrische Salate mit hausgemachtem Balsamico- oder Joghurtdressing", order: 3 },
      { id: "cat_drinks", name: "Getränke", description: "Eiskalte Erfrischungen und italienische Limonaden", order: 4 },
    ],
    items: [
      {
        id: "item_piz_1",
        categoryId: "cat_piz",
        number: "01",
        name: "Pizza Margherita",
        description: "Fior di Latte Mozzarella, San Marzano Tomatensauce, frisches Basilikum, Olivenöl",
        basePrice: 8.50,
        vatRate: 7,
        allergens: ["A", "G"],
        isSoldOut: false,
        order: 1,
        sizes: [
          { id: "s_std", name: "Ø 28 cm Klassik", price: 8.50 },
          { id: "s_fam", name: "Ø 34 cm Maxi (+3,50 €)", price: 12.00 },
        ],
        extraGroups: [
          {
            id: "eg_cheese",
            name: "Käse-Extras",
            required: false,
            multiple: true,
            extras: [
              { id: "ex_bufala", name: "Büffelmozzarella D.O.P.", price: 2.50 },
              { id: "ex_gorgonzola", name: "Gorgonzola D.O.P.", price: 2.00 },
            ],
          },
        ],
      },
      {
        id: "item_piz_2",
        categoryId: "cat_piz",
        number: "02",
        name: "Pizza Salame Piccante",
        description: "Scharfe kalabrische Salami, San Marzano Tomaten, Fior di Latte Mozzarella",
        basePrice: 11.50,
        vatRate: 7,
        allergens: ["A", "G"],
        isSoldOut: false,
        order: 2,
        sizes: [
          { id: "s_std_2", name: "Ø 28 cm Klassik", price: 11.50 },
          { id: "s_fam_2", name: "Ø 34 cm Maxi (+3,50 €)", price: 15.00 },
        ],
        extraGroups: [],
      },
      {
        id: "item_pasta_1",
        categoryId: "cat_pasta",
        number: "20",
        name: "Penne all'Arrabbiata",
        description: "Würzige Tomatensauce mit Knoblauch, Peperoncino und frischer Petersilie",
        basePrice: 9.90,
        vatRate: 7,
        allergens: ["A", "G"],
        isSoldOut: false,
        order: 3,
        sizes: [],
        extraGroups: [
          {
            id: "eg_pasta_cheese",
            name: "Parmigiano Reggiano",
            required: false,
            multiple: false,
            extras: [{ id: "ex_parm", name: "Frisch geriebener Parmesan", price: 1.50 }],
          },
        ],
      },
      {
        id: "item_drk_1",
        categoryId: "cat_drinks",
        number: "90",
        name: "San Pellegrino 0,5l",
        description: "Italienisches Mineralwasser mit Kohlensäure",
        basePrice: 2.80,
        vatRate: 19,
        allergens: [],
        isSoldOut: false,
        order: 4,
        sizes: [],
        extraGroups: [],
      },
    ],
  },
  {
    id: "template_imbiss_burger",
    name: "Burger & Döner Imbiss Express",
    description: "Saftige Burger, Döner Kebab, Dürüm, knusprige Pommes frites und Softdrinks.",
    icon: "🍔",
    defaultAccentColor: "#e11d48",
    categories: [
      { id: "cat_burger", name: "Smash Burger & Classics", description: "100% deutsches Rindfleisch, frisch gegrillt im Brioche-Bun", order: 1 },
      { id: "cat_doener", name: "Döner & Dürüm", description: "Täglich frischer Drehspieß im knusprigen Fladenbrot", order: 2 },
      { id: "cat_fries", name: "Beilagen & Fingerfood", description: "Knusprig frittiert mit hausgemachten Saucen", order: 3 },
      { id: "cat_drinks_imbiss", name: "Kalte Getränke", description: "Erfrischende Dosen und Flaschen", order: 4 },
    ],
    items: [
      {
        id: "item_b_1",
        categoryId: "cat_burger",
        number: "B01",
        name: "Double Cheese Smash Burger",
        description: "2x 100g Rinderpatties, Cheddar, hausgemachte Burgersauce, Gurken, rote Zwiebeln im Brioche-Bun",
        basePrice: 9.50,
        vatRate: 7,
        allergens: ["A", "C", "G", "J"],
        isSoldOut: false,
        order: 1,
        sizes: [
          { id: "s_single", name: "Einzelburger", price: 9.50 },
          { id: "s_menu", name: "Im Menü mit Pommes & Softdrink (+4,50 €)", price: 14.00 },
        ],
        extraGroups: [
          {
            id: "eg_burger_extras",
            name: "Zusätzliche Toppings",
            required: false,
            multiple: true,
            extras: [
              { id: "ex_bacon", name: "Knuspriger Bacon", price: 1.50 },
              { id: "ex_jalapeno", name: "Jalapeños scharf", price: 0.80 },
            ],
          },
        ],
      },
      {
        id: "item_d_1",
        categoryId: "cat_doener",
        number: "D01",
        name: "Original Berliner Döner Kebab",
        description: "Knuspriges Fladenbrot, Kalbfleisch oder Hähnchen, Eisbergsalat, Tomate, Gurke, Zwiebeln, Knoblauchsauce",
        basePrice: 7.50,
        vatRate: 7,
        allergens: ["A", "G", "K"],
        isSoldOut: false,
        order: 2,
        sizes: [],
        extraGroups: [
          {
            id: "eg_doener_sauce",
            name: "Sauce wählen",
            required: true,
            multiple: false,
            extras: [
              { id: "ex_kraeuter", name: "Kräutersauce", price: 0 },
              { id: "ex_knobi", name: "Knoblauchsauce", price: 0 },
              { id: "ex_scharf", name: "Scharfe Chilisauce", price: 0 },
            ],
          },
        ],
      },
      {
        id: "item_f_1",
        categoryId: "cat_fries",
        number: "F01",
        name: "Knusprige Pommes Frites (Groß)",
        description: "Goldgelb frittierte Kartoffelstäbchen mit Pommessalz",
        basePrice: 3.90,
        vatRate: 7,
        allergens: [],
        isSoldOut: false,
        order: 3,
        sizes: [],
        extraGroups: [],
      },
      {
        id: "item_cola_imbiss",
        categoryId: "cat_drinks_imbiss",
        number: "G01",
        name: "Coca-Cola 0,33l Dose",
        description: "Koffeinhaltiges Erfrischungsgetränk",
        basePrice: 2.50,
        vatRate: 19,
        allergens: [],
        isSoldOut: false,
        order: 4,
        sizes: [],
        extraGroups: [],
      },
    ],
  },
  {
    id: "template_asia_wok",
    name: "Asia Wok & Nudel-Küche",
    description: "Gebratene Nudeln, duftende Thai-Currys, Frühlingsrollen und asiatische Spezialitäten.",
    icon: "🥢",
    defaultAccentColor: "#059669",
    categories: [
      { id: "cat_wok", name: "Gebratene Nudeln & Reis", description: "Auf heißen Wok-Flammen frisch gewokt mit knackigem Gemüse", order: 1 },
      { id: "cat_curry", name: "Traditionelle Thai Currys", description: "Feine Kokosmilchsaucen mit Jasmin-Duftreis", order: 2 },
      { id: "cat_starters", name: "Vorspeisen & Fingerfood", description: "Hausgemachte Frühlingsrollen, Gyoza und Wantans", order: 3 },
      { id: "cat_drinks_asia", name: "Asiatische Getränke", description: "Mango-Lassi, Jasmintee und Softdrinks", order: 4 },
    ],
    items: [
      {
        id: "item_wok_1",
        categoryId: "cat_wok",
        number: "W01",
        name: "Gebratene Eiernudeln mit knuspriger Ente",
        description: "Mit frischen Sojasprossen, Karotten, Lauch, Röstzwiebeln und pikanter dunkler Wok-Sauce",
        basePrice: 13.90,
        vatRate: 7,
        allergens: ["A", "C", "F"],
        isSoldOut: false,
        order: 1,
        sizes: [],
        extraGroups: [
          {
            id: "eg_sauce_asia",
            name: "Sauce wählen",
            required: false,
            multiple: false,
            extras: [
              { id: "ex_suess_sauer", name: "Süß-Sauer Dip", price: 1.00 },
              { id: "ex_erdnuss", name: "Warme Erdnusssauce", price: 1.80 },
            ],
          },
        ],
      },
      {
        id: "item_curry_1",
        categoryId: "cat_curry",
        number: "C01",
        name: "Gelbes Thai Curry mit zartem Hähnchen",
        description: "Cremige Kokos-Currysauce, Bambusstreifen, Karotten, Paprika und gedämpfter Jasminreis",
        basePrice: 11.50,
        vatRate: 7,
        allergens: ["F"],
        isSoldOut: false,
        order: 2,
        sizes: [],
        extraGroups: [],
      },
      {
        id: "item_start_1",
        categoryId: "cat_starters",
        number: "V01",
        name: "6x Mini-Frühlingsrollen (Vegetarisch)",
        description: "Mit knackiger Gemüsefüllung und Süß-Sauer-Dip serviert",
        basePrice: 4.50,
        vatRate: 7,
        allergens: ["A", "F"],
        isSoldOut: false,
        order: 3,
        sizes: [],
        extraGroups: [],
      },
      {
        id: "item_lassi_1",
        categoryId: "cat_drinks_asia",
        number: "T01",
        name: "Hausgemachter Mango-Lassi 0,4l",
        description: "Erfrischender indischer Joghurt-Drink mit reifer Alphonso-Mango",
        basePrice: 3.80,
        vatRate: 19,
        allergens: ["G"],
        isSoldOut: false,
        order: 4,
        sizes: [],
        extraGroups: [],
      },
    ],
  },
];
